### ISSUE TITLE
Animated item spinning way to fast

### ISSUE THREAD

**Issue by Cape-City** [Patbox/UniversalShops#11]
Hi,

I'm using MC 1.19.3 on fabric and the animated item over the block is spinning way to fast
and could be a bit higher than actually or better be configurable via preffile or within MC.

https://user-images.githubusercontent.com/122229367/232323936-970d8938-c466-4ef6-9587-9469072b2360.mp4

Also the hovering text is visiable through walls:

![2023-04-16_17 41 02](https://user-images.githubusercontent.com/122229367/232324134-205b9d80-bb6e-4546-8e3a-6426a278b27c.png)

**Comment by Patbox** [comment]
Issue with some other mod you have likely (since it is server side and uses vanilla item entity on client). Second one is also fixed in 1.19.4 (can't be before)

**Comment by Cape-City** [comment]
Ok, thanks for answering. At the moment i can't update to 1.19.4 'coz some important mods i have installed, aren't available yet for 1.19.4. I will wait and when up on 1.19.4 i will give your mod another visit back.
