### ISSUE TITLE
Player head remains after breaking own shop block

### ISSUE THREAD

**Issue by kristinjkristin** [Patbox/UniversalShops#13]
![huge_2023-05-13_14 39 21](https://github.com/Patbox/UniversalShops/assets/132313585/c174622b-3284-4be6-a02c-1651a8e81753)

even after removing my shop block, a steve player head remains.

**Comment by Patbox** [comment]
Looks like desync (no texture). Also check if you didn't left currency there, as it prevents breaking (it needs to be empty). If it still doesn't work, check logs and report any errors
