### ISSUE TITLE
Duping possible when withdrawing items from currency storage

### ISSUE THREAD

**Issue by sahmed011** [Patbox/UniversalShops#15]
I love this mod, but I don't want a dupe possible on my server! Basically what happens is if you withdraw say 5 diamond blocks from the currency storage then quickly store it in a chest, you can _again_ withdraw the 5 diamond blocks. idk what other info to put here 
EDIT: i should mention that this is on a 1.19.2 fabric server

**Comment by Patbox** [comment]
Hey, could you send a video showcasing it?

**Comment by sahmed011** [comment]
Sure, I'll do it as soon as I can :D

**Comment by Patbox** [comment]
Also does it happen in survival?

**Comment by sahmed011** [comment]
It does happen in survival. I cannot provide footage right now as it is quite difficult to replicate and both people including myself who did the dupe forgot how to... I'll figure it out as soon as I can sorry.

**Comment by Patbox** [comment]
Closing for now. It's highly likely the bug was purely visual (client/server desync) so it wasn't actually duping anything (and if you were on creative, client likes to force-set slots a lot so it could make these items real, but thats creative only thing)
