### ISSUE TITLE
[BUG] two shops owned by same person

### ISSUE THREAD

**Issue by GamingInfinite** [Patbox/UniversalShops#16]
A player on my server was setting up multiple servers in which the item for purchase was gold ingots and somewhere you could buy gold ingots for something else.  However whenever he modifies, or even sets up another shop using gold ingots it changes all of the shops to that amount, both input and output.  Probably something with the way you're storing the shop data.

**Comment by Patbox** [comment]
It only happens if you use generic selector instead of clicking with item. But good catch
