### ISSUE TITLE
Crash with FTB XMod Compat if FTB Chunks is not present

### ISSUE THREAD

**Issue by jmadarg** [Patbox/UniversalShops#23]
On a modpack that uses OPAC for claims (so no FTB Chunks) we were having the following crash https://mclo.gs/fx4jcWQ
The pack did include FTB XMod compat, as its required for other FTB Mods but it seems like the shop tries to look for FTB Chunks when only XMod is there, causing this crash (at least that is my guess)
Once FTB Xmod Compat was disabled, there was no further issues.

**Comment by Patbox** [comment]
This is issue with ftbxmodcompat and I can't fix it. It will effect any mod using common protection api

**Comment by jmadarg** [comment]
Understood, will report to them
