### ISSUE TITLE
not compatible with fabric geyser

### ISSUE THREAD

**Issue by oldsheep0205** [Patbox/UniversalShops#28]
After I add an admin shop, I cannot join the server from bedrock edition using geyser. my edition is 1.21.1 now. How can I fix it?

**Comment by oldsheep0205** [comment]
I find the problem. two shop blocks has to be registerd in bedrock. Can u share the jsons?

**Comment by Patbox** [comment]
Report it to geyser people, as it should work just fine

**Comment by oldsheep0205** [comment]
Do I need to install Polymer first?

**Comment by oldsheep0205** [comment]
When I delete polymer and universal shop, I can join bedrock

**Comment by oldsheep0205** [comment]
Console output: register bedrock skins... and then nothing happen, then client said connection closed.

**Comment by Patbox** [comment]
https://github.com/GeyserMC/Geyser/issues/4831
