### ISSUE TITLE
Could you please add a Chinese translation?

### ISSUE THREAD

**Issue by whydm2003724** [Patbox/UniversalShops#34]
Thank you for your creation, I hope you can add Chinese.

**Comment by HY916-cn** [comment]
别说洋文，小企鹅2521007819我有汉化版

**Comment by HY916-cn** [comment]
收到了就把Issues关闭了占作者时间

**Comment by whydm2003724** [comment]
> 收到了就把Issues关闭了占作者时间

好的，谢谢了，用的翻译，其实我不太会英语哈哈

**Comment by HY916-cn** [comment]
> > 了并将问题关闭了占收到作者时间
> 
> 好的，谢谢了，用的翻译，其实我不太会英语哈哈

加我q我发你
