### ISSUE TITLE
Users can steal from storage

### ISSUE THREAD

**Issue by LuxTheFox** [Patbox/UniversalShops#9]
Users can steal for the supply container/storage, Its yeah just that- Shouldnt be that hard to fix If I know the fabric api correctly-

**Comment by Patbox** [comment]
Could you tell me how they can steal it? I don't have enough info

**Comment by LuxTheFox** [comment]
Looking through your code, It may not be as simple to fix as I thought
Anywho they can literally just open the supply chest/barrel and take items out

**Comment by LuxTheFox** [comment]
Ah alright, It would be cool if it was added in the mod itself, I dont think it would be that hard just store all the shop containers positions in an array like `new int[][]{{x,y,z}, {x,y,z}}` and on PlayerBlockBreakEvents.BEFORE register an event to check if its any of those positions above and if it is return false otherwise return true, That should stop it from being broken and you can basically the same thing on UseBlockCallback but returning ActionResult.PASS as true and ActionResult.FAIL as false

**Comment by LuxTheFox** [comment]
or better idea, Add an NBT tag to the container and when a block is broken with an NBT tag then just cancel the break, Actually I could deff make a fork/PR to add that

**Comment by Patbox** [comment]
You still be better just using alternative methods, as this mod is compatible with them
